[supervisord]
nodaemon=true

[program:xvfb]

[program:xvfb]
command=Xvfb :0 -screen 0 800x600x16

[program:fluxbox]
command=fluxbox -display :0
autorestart=true
environment=DISPLAY=":0"

[program:x11vnc]
command=x11vnc -display :0 -forever -shared -nopw
autorestart=true

[program:websockify]
command=websockify --web=/usr/share/novnc/ PORT localhost:5900
autorestart=true

[program:firefox]
command=firefox --display=:0 --no-remote --safe-mode
