[supervisord]
nodaemon=true

[program:xvfb]
command=Xvfb :0 -screen 0 1024x768x16
autorestart=true

[program:fluxbox]
command=fluxbox -display :0
autorestart=true
environment=DISPLAY=":0"

[program:x11vnc]
command=x11vnc -display :0 -forever -shared -nopw
autorestart=true

[program:novnc_files]
command=/usr/share/novnc/utils/launch.sh --listen 6080 --vnc localhost:5900
autorestart=true

[program:node_bridge]
command=node /root/noVNC/bridge.js
autorestart=true

[program:firefox]
command=firefox --display=:0 --no-remote --safe-mode
autorestart=true
